### ISSUE TITLE
Date conversion broken in newer versions of nc-time-axis

### ISSUE THREAD

**Issue by jkrasting** [jkrasting/gfdlvitals#11]
Newer versions of `nc-time-axis` give the following error:

```
Traceback (most recent call last):
  File "/net/jpk/miniconda3/envs/py39/lib/python3.9/site-packages/matplotlib/axis.py", line 1506, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "/net/jpk/miniconda3/envs/py39/lib/python3.9/site-packages/nc_time_axis/__init__.py", line 278, in convert
    raise ValueError('The values must be numbers or instances of '
ValueError: The values must be numbers or instances of "nc_time_axis.CalendarDateTime" or "cftime.datetime".

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/net/jpk/miniconda3/envs/py39/bin/plotdb", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/jpk/pkgs/gfdlvitals/scripts/plotdb", line 85, in <module>
    gfdlvitals.plot.run_plotdb(cliargs)
  File "/home/jpk/pkgs/gfdlvitals/gfdlvitals/plot.py", line 359, in run_plotdb
    mplfig, axes = gfdlvitals.plot.plot_timeseries(
  File "/home/jpk/pkgs/gfdlvitals/gfdlvitals/plot.py", line 147, in plot_timeseries
    (axes_dict[label]["line"],) = _ax.plot(
  File "/net/jpk/miniconda3/envs/py39/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 1632, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/net/jpk/miniconda3/envs/py39/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 312, in __call__
    yield from self._plot_args(this, kwargs)
  File "/net/jpk/miniconda3/envs/py39/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 493, in _plot_args
    self.axes.xaxis.update_units(x)
  File "/net/jpk/miniconda3/envs/py39/lib/python3.9/site-packages/matplotlib/axis.py", line 1451, in update_units
    self.set_units(default)
  File "/net/jpk/miniconda3/envs/py39/lib/python3.9/site-packages/matplotlib/axis.py", line 1537, in set_units
    axis._update_axisinfo()
  File "/net/jpk/miniconda3/envs/py39/lib/python3.9/site-packages/matplotlib/axis.py", line 1490, in _update_axisinfo
    self.set_default_intervals()
  File "/net/jpk/miniconda3/envs/py39/lib/python3.9/site-packages/matplotlib/axis.py", line 2257, in set_default_intervals
    xmin, xmax = self.convert_units(info.default_limits)
  File "/net/jpk/miniconda3/envs/py39/lib/python3.9/site-packages/matplotlib/axis.py", line 1508, in convert_units
    raise munits.ConversionError('Failed to convert value(s) to axis '
matplotlib.units.ConversionError: Failed to convert value(s) to axis units: (<CalendarDateTime: datetime=2000-01-01 00:00:00, calendar=noleap>, <CalendarDateTime: datetime=2010-01-01 00:00:00, calendar=noleap>)
```

**Comment by jkrasting** [comment]
Issues fixed with newer versions of nc-time-axis.
